# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoevent', '0006_auto_20151209_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_office_box', models.CharField(blank=True, max_length=1024, verbose_name='post office box')),
                ('extended_address', models.CharField(blank=True, max_length=1024, verbose_name='extended address')),
                ('street_address', models.CharField(max_length=1024, verbose_name='street address')),
                ('locality', models.CharField(max_length=1024, verbose_name='locality')),
                ('region', models.CharField(max_length=1024, verbose_name='region')),
                ('postal_code', models.CharField(max_length=1024, verbose_name='postal code')),
                ('country_name', models.CharField(max_length=1024, verbose_name='country name')),
                ('type', models.CharField(choices=[('INTL', 'INTL'), ('POSTAL', 'postal'), ('PARCEL', 'parcel'), ('WORK', 'work'), ('dom', 'dom'), ('home', 'home'), ('pref', 'pref')], max_length=1024, verbose_name='type')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fburl', models.CharField(max_length=2000)),
                ('fn', models.CharField(max_length=2000)),
                ('n', models.CharField(max_length=2000)),
                ('kind', models.CharField(max_length=2000)),
                ('prodid', models.CharField(max_length=2000)),
                ('uid', models.CharField(max_length=2000)),
                ('version', models.CharField(max_length=2000)),
                ('x_ablabel', models.CharField(max_length=2000)),
                ('x_abuid', models.CharField(max_length=2000)),
                ('x_evolution_assistant', models.CharField(max_length=2000)),
                ('x_evolution_blog_url', models.CharField(max_length=2000)),
                ('x_evolution_file_as', models.CharField(max_length=2000)),
                ('x_evolution_manager', models.CharField(max_length=2000)),
                ('x_evolution_spouse', models.CharField(max_length=2000)),
                ('x_evolution_video_url', models.CharField(max_length=2000)),
                ('x_evolution_webdav_href', models.CharField(max_length=2000)),
                ('x_linguistlist_editingstatus', models.CharField(max_length=2000)),
                ('x_linguistlist_editorapproval', models.CharField(max_length=2000)),
                ('x_linguistlist_institutionid', models.CharField(max_length=2000)),
                ('x_linguistlist_progalternatename', models.CharField(max_length=2000)),
                ('x_linguistlist_progappdeadline', models.CharField(max_length=2000)),
                ('x_linguistlist_progdescr', models.CharField(max_length=2000)),
                ('x_linguistlist_progdistinctions', models.CharField(max_length=2000)),
                ('x_linguistlist_progeditorcomment', models.CharField(max_length=2000)),
                ('x_linguistlist_progfinancialaid', models.CharField(max_length=2000)),
                ('x_linguistlist_programmid', models.CharField(max_length=2000)),
                ('x_linguistlist_progsize', models.CharField(max_length=2000)),
                ('x_linguistlist_progspecial', models.CharField(max_length=2000)),
                ('x_linguistlist_progstatus', models.CharField(max_length=2000)),
                ('x_linguistlist_progtitle', models.CharField(max_length=2000)),
                ('x_mozilla_html', models.CharField(max_length=2000)),
                ('x_radicale_name', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INTERNET', 'internet'), ('x400', 'x400'), ('pref', 'pref')], max_length=30, verbose_name='type of email')),
                ('value', models.EmailField(max_length=100, verbose_name='value')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoevent.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=2000)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoevent.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Nickname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=100)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoevent.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=1024, verbose_name='organization name')),
                ('organization_unit', models.CharField(blank=True, max_length=1024, verbose_name='organization unit')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoevent.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=100)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoevent.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Tel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('VOICE', 'INTL'), ('HOME', 'home'), ('MSG', 'message'), ('WORK', 'work'), ('pref', 'prefered'), ('fax', 'fax'), ('cell', 'cell phone'), ('video', 'video'), ('pager', 'pager'), ('bbs', 'bbs'), ('modem', 'modem'), ('car', 'car phone'), ('isdn', 'isdn'), ('pcs', 'pcs')], help_text='for instance WORK or HOME', max_length=30, verbose_name='type of phone number')),
                ('value', models.CharField(max_length=100, verbose_name='value')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoevent.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.URLField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoevent.Contact')),
            ],
        ),
        migrations.AddField(
            model_name='adr',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoevent.Contact'),
        ),
    ]
