# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoevent', '0007_auto_20160711_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INTERNET', 'internet'), ('x400', 'x400'), ('pref', 'pref')], max_length=30, verbose_name='type of email')),
            ],
        ),
        migrations.CreateModel(
            name='Tel_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('VOICE', 'INTL'), ('HOME', 'home'), ('MSG', 'message'), ('WORK', 'work'), ('pref', 'prefered'), ('fax', 'fax'), ('cell', 'cell phone'), ('video', 'video'), ('pager', 'pager'), ('bbs', 'bbs'), ('modem', 'modem'), ('car', 'car phone'), ('isdn', 'isdn'), ('pcs', 'pcs')], help_text='for instance WORK or HOME', max_length=30, verbose_name='type of phone number')),
            ],
        ),
        migrations.RemoveField(
            model_name='email',
            name='type',
        ),
        migrations.RemoveField(
            model_name='tel',
            name='type',
        ),
        migrations.AddField(
            model_name='tel_type',
            name='tel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoevent.Tel'),
        ),
        migrations.AddField(
            model_name='email_type',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoevent.Email'),
        ),
    ]
