# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoevent', '0008_auto_20160714_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adr_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INTL', 'INTL'), ('POSTAL', 'postal'), ('PARCEL', 'parcel'), ('WORK', 'work'), ('dom', 'dom'), ('home', 'home'), ('pref', 'pref')], max_length=1024, verbose_name='type')),
            ],
        ),
        migrations.RemoveField(
            model_name='adr',
            name='type',
        ),
        migrations.AddField(
            model_name='adr_type',
            name='adr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoevent.Adr'),
        ),
    ]
