# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoevent', '0010_auto_20160719_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='x_linguistlist_progfinancialaid',
            field=models.TextField(),
        ),
    ]
