# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoevent', '0011_auto_20160719_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='adr',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='adr',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
