# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoevent', '0013_auto_20160721_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='geoevent.Contact'),
        ),
        migrations.AlterField(
            model_name='label',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labales', to='geoevent.Contact'),
        ),
        migrations.AlterField(
            model_name='nickname',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nicknames', to='geoevent.Contact'),
        ),
        migrations.AlterField(
            model_name='org',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='geoevent.Contact'),
        ),
        migrations.AlterField(
            model_name='role',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='geoevent.Contact'),
        ),
        migrations.AlterField(
            model_name='tel',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tels', to='geoevent.Contact'),
        ),
        migrations.AlterField(
            model_name='url',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='geoevent.Contact'),
        ),
    ]
