# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoevent', '0014_auto_20160722_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='geoevent.Contact'),
        ),
        migrations.AlterField(
            model_name='org',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgs', to='geoevent.Contact'),
        ),
    ]
