# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoevent', '0015_auto_20160722_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='data',
            field=models.TextField(),
        ),
    ]
