# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-04 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoevent', '0016_auto_20160722_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adr_type',
            name='adr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adr_types', to='geoevent.Adr'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='fburl',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='fn',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='kind',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='n',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='prodid',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='uid',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='version',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='x_ablabel',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='x_abuid',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='x_evolution_assistant',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='x_evolution_blog_url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='x_evolution_file_as',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='x_evolution_manager',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='x_evolution_spouse',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='x_evolution_video_url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='x_evolution_webdav_href',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='x_linguistlist_editingstatus',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='x_linguistlist_editorapproval',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='x_linguistlist_institutionid',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='x_linguistlist_progalternatename',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='x_linguistlist_progappdeadline',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='x_linguistlist_progdescr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='x_linguistlist_progdistinctions',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='x_linguistlist_progeditorcomment',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='x_linguistlist_progfinancialaid',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='x_linguistlist_programmid',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='x_linguistlist_progsize',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='x_linguistlist_progspecial',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='x_linguistlist_progstatus',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='x_linguistlist_progtitle',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='x_mozilla_html',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='x_radicale_name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='email_type',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_types', to='geoevent.Email'),
        ),
        migrations.AlterField(
            model_name='event',
            name='dend',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='dstart',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='due',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(help_text='Please put in the address of the event so that your event will show up on the map.', max_length=1024, verbose_name='Local Address'),
        ),
        migrations.AlterField(
            model_name='tel_type',
            name='tel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tel_types', to='geoevent.Tel'),
        ),
    ]
