# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-04 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoevent', '0017_auto_20170104_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='data',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='nickname',
            name='data',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='data',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
