# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoevent', '0018_auto_20170104_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text='You can use Markdown syntax for formatting.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.TextField(help_text='Please put in the address of the event so that your event will show up on the map.', verbose_name='Local Address'),
        ),
    ]
